name: Package AOS for nightly

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build initial zips
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Install p7zip for nesDS
        run: |
          sudo apt update
          sudo apt install p7zip-full -y

      - name: Download other applications
        run: |
          mkdir -p extras_external
          cd extras_external
          wget https://github.com/wavemotion-dave/A8DS/releases/latest/download/A8DS.nds
          wget https://github.com/wavemotion-dave/StellaDS/releases/latest/download/StellaDS.nds
          wget https://github.com/wavemotion-dave/A5200DS/releases/latest/download/A5200DS.nds
          wget https://github.com/wavemotion-dave/A7800DS/releases/latest/download/A7800DS.nds
          wget https://github.com/wavemotion-dave/ColecoDS/releases/latest/download/ColecoDS.nds
          wget https://github.com/FluBBaOfWard/S8DS/releases/latest/download/S8DS.zip
          wget -O GBARunner2.nds https://github.com/unresolvedsymbol/GBARunner2-DSL-Enhanced/releases/download/v20201019-DSL_97447fe/GBARunner2_arm9dldi_ds.nds
          wget https://files.deletecat.com/GBARunner3.zip
          wget -O GBAR3-Frontend.nds https://github.com/flashcarts/gbar3-frontend/releases/download/v0.9.0-fcnet2/gbar3-frontend-AOS.nds
          wget https://github.com/Stewmath/GameYob/releases/download/v0.5.2/gameyob.zip
          wget https://github.com/DS-Homebrew/NesDS/releases/latest/download/nesDS.7z
          unzip GBARunner3.zip
          cp -r _gba ../out/acep
          cp -r _gba ../out/r4it
          cp -r _gba ../out/r4xx
          cp -r _gba ../out/ex4ds
          unzip gameyob.zip; rm gameyob_dsi.nds
          unzip S8DS.zip
          7z e nesDS.7z
          # for whatever reason this needs to be DLDI patched, doesn't want to work from AOS directly
          dlditool ../kernel/__rpg/game.dldi gameyob.nds
          cp -r *.nds ../out/acep/__rpg/APP/
          cp -r *.nds ../out/r4it/__rpg/APP/
          cp -r *.nds ../out/r4xx/__rpg/APP/
          cp -r *.nds ../out/ex4ds/__rpg/APP/

      - name: Package individual kernel files
        run: |
          cd out/acep
          zip -r ../AOS_Ace3DSPlus.zip *
          cd ../r4it
          zip -r ../AOS_Gateway.zip *
          cd ../r4xx
          zip -r ../AOS_R4iLS.zip *
          cd ../ex4ds
          zip -r ../AOS_EX4DS.zip *

      - name: Prepare for publishing
        run: |
          mkdir -p ~/artifacts
          cp out/AOS_*.zip ~/artifacts

      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: ~/artifacts/*
          name: build
