name: Package AOS for release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build initial zips
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Install p7zip for nesDS
        run: |
          sudo apt update
          sudo apt install p7zip-full -y

      - name: Download other applications
        run: |
          mkdir -p extras_external
          cd extras_external
          wget https://github.com/wavemotion-dave/A8DS/releases/latest/download/A8DS.nds
          wget https://github.com/wavemotion-dave/StellaDS/releases/latest/download/StellaDS.nds
          wget https://github.com/wavemotion-dave/A5200DS/releases/latest/download/A5200DS.nds
          wget https://github.com/wavemotion-dave/A7800DS/releases/latest/download/A7800DS.nds
          wget https://github.com/wavemotion-dave/ColecoDS/releases/latest/download/ColecoDS.nds
          wget https://github.com/FluBBaOfWard/S8DS/releases/latest/download/S8DS.zip
          wget -O GBARunner2.nds https://github.com/unresolvedsymbol/GBARunner2-DSL-Enhanced/releases/download/v20201019-DSL_97447fe/GBARunner2_arm9dldi_ds.nds
          wget https://nightly.link/Gericom/GBARunner3/workflows/nightly/develop/GBARunner3.zip
          wget -O GBAR3-Frontend.nds https://github.com/flashcarts/gbar3-frontend/releases/download/v0.9.0-fcnet1/gbar3-frontend-AOS.nds
          wget https://github.com/Stewmath/GameYob/releases/download/v0.5.2/gameyob.zip
          wget https://github.com/DS-Homebrew/NesDS/releases/latest/download/nesDS.7z
          unzip GBARunner3.zip
          cp -r _gba ../out/acep
          cp -r _gba ../out/r4it
          cp -r _gba ../out/r4xx
          unzip gameyob.zip; rm gameyob_dsi.nds
          unzip S8DS.zip
          7z e nesDS.7z
          # for whatever reason this needs to be DLDI patched, doesn't want to work from AOS directly
          dlditool ../kernel/__rpg/game.dldi gameyob.nds
          cp -r *.nds ../out/acep/__rpg/APP/
          cp -r *.nds ../out/r4it/__rpg/APP/
          cp -r *.nds ../out/r4xx/__rpg/APP/

      - name: Package individual kernel files
        run: |
          cd out/acep
          zip -r ../AOS_Ace3DSPlus.zip *
          cd ../r4it
          zip -r ../AOS_Gateway.zip *
          cd ../r4xx
          zip -r ../AOS_R4iLS.zip *

      - name: Prepare for publishing
        run: |
          mkdir -p ~/artifacts
          cp out/AOS_*.zip ~/artifacts

      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v3
        with:
          path: ~/artifacts/*
          name: build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/AOS_Ace3DSPlus.zip
            out/AOS_Gateway.zip
            out/AOS_R4iLS.zip
            README.md
